---

### 🎓 **Professor**: Apostolos Filippas

### 📘 **Class**: E-Commerce

### 📋 **Topic**: DataFrames and Analyzing Data with Python

🚫 **Note**: You are not allowed to share the contents of this notebook with anyone outside this class without written permission by the professor.

---

# PART 1

**Topic**: We will learn the most useful data structure in Python: the DataFrame. We will also see how easy it is to read and write data using Python/pandas

## 1. DataFrames

DataFrames can be thought of as Excel sheets on steroids:
- Each row refers to an observation: (entity, purchase, review, user, ...)
- Each column refers to an attribute of the observation (e.g. age, height, ...)
- The first row usually has the names of each column

In [39]:
# 1.1 Creating a DataFrame

# First, let's import pandas
import pandas as pd

# To make a DataFrame
test_scores = [19, 18, 20, 20, 17]
quiz_scores = [18, 17, 19, 20, 20]
names = ["Apostolos", "Margarita", "Tyler", "Ronny", "Natalie"]

# Python automatically names the columns of the DataFrame according to the dictionary keys
df = pd.DataFrame(
    {"test_scores": test_scores, "quiz_scores": quiz_scores, "names": names}
)
print(df)

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
2           20           19      Tyler
3           20           20      Ronny
4           17           20    Natalie

In [40]:
# 1.2 Viewing DataFrames

# The head() function prints the first 5 lines of the DataFrame
# For DataFrames with millions of rows, this will be important...
df.head()

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
2           20           19      Tyler
3           20           20      Ronny
4           17           20    Natalie

In [41]:
df.head(2)

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita

In [42]:
# Similarly, the tail() function prints the last 5 rows
# If your df is very small, they will be the same :)
df.tail()

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
2           20           19      Tyler
3           20           20      Ronny
4           17           20    Natalie

In [43]:
df.tail(3)

   test_scores  quiz_scores    names
2           20           19    Tyler
3           20           20    Ronny
4           17           20  Natalie

In [44]:
# 1.3 Getting information about a DataFrame

# To access any column of a DataFrame
df["test_scores"]

0    19
1    18
2    20
3    20
4    17
Name: test_scores, dtype: int64

In [45]:
df["names"]

0    Apostolos
1    Margarita
2        Tyler
3        Ronny
4      Natalie
Name: names, dtype: object

In [46]:
# A useful way to summarize a DataFrame fast
df.describe()

       test_scores  quiz_scores
count      5.00000      5.00000
mean      18.80000     18.80000
std        1.30384      1.30384
min       17.00000     17.00000
25%       18.00000     18.00000
50%       19.00000     19.00000
75%       20.00000     20.00000
max       20.00000     20.00000

In [47]:
# Types of each column
df.dtypes

test_scores     int64
quiz_scores     int64
names          object
dtype: object

In [48]:
# More detailed information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   test_scores  5 non-null      int64
 1   quiz_scores  5 non-null      int64
 2   names        5 non-null      object
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [49]:
# How many observations (rows)
print(df.shape[0])  # or len(df)
# How many columns
print(df.shape[1])  # or len(df.columns)
# Names of rows (index)
print(df.index.tolist())
# Names of columns
print(df.columns.tolist())

5
3
[0, 1, 2, 3, 4]
['test_scores', 'quiz_scores', 'names']

In [50]:
# 1.4 Changing a DataFrame

# You can create a new column in the DataFrame as follows
df["new_column"] = df["quiz_scores"] + 2
df

   test_scores  quiz_scores      names  new_column
0           19           18  Apostolos          20
1           18           17  Margarita          19
2           20           19      Tyler          21
3           20           20      Ronny          22
4           17           20    Natalie          22

In [51]:
# You can delete a column in the DataFrame by using drop()
df = df.drop("new_column", axis=1)
df.head()

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
2           20           19      Tyler
3           20           20      Ronny
4           17           20    Natalie

In [52]:
# 1.5 Accessing subsets of your DataFrame

# You can access rows and columns directly
# In pandas, we use .loc[] for label-based indexing and .iloc[] for position-based indexing

# Select specific rows and columns by position
print(df.iloc[0:4]["quiz_scores"])  # rows 0-3, quiz_scores column
print(df.iloc[[0, 1, 3]])  # rows 0, 1, 3, all columns
print(df.iloc[0:4, 0:2])  # rows 0-3, columns 0-1

0    18
1    17
2    19
3    20
Name: quiz_scores, dtype: int64
   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
3           20           20      Ronny
   test_scores  quiz_scores
0           19           18
1           18           17
2           20           19
3           20           20

We can select only those rows that satisfy a condition

In [53]:
# Select rows that have test_scores greater than 19
df[df["test_scores"] > 19]

   test_scores  quiz_scores  names
2           20           19  Tyler
3           20           20  Ronny

In [20]:
df

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17        Aja
2           20           19      Calai
3           20           20   Katalina
4           17           20        Cal

In [55]:
# Select rows with either test score > 19 OR quiz score <= 18
df[(df["test_scores"] > 19) | (df["quiz_scores"] <= 18)]

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
2           20           19      Tyler
3           20           20      Ronny

In [56]:
# Select rows with either test score > 19 AND quiz score <= 18
df[(df["test_scores"] > 19) & (df["quiz_scores"] <= 18)]

Empty DataFrame
Columns: [test_scores, quiz_scores, names]
Index: []

In [57]:
# Select rows with test score less or equal to 19
df[df["test_scores"] <= 19]

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
4           17           20    Natalie

In [58]:
df[~(df["test_scores"] > 19)]  # ~ is the negation operator

   test_scores  quiz_scores      names
0           19           18  Apostolos
1           18           17  Margarita
4           17           20    Natalie

In [59]:
# Select rows with test scores equal to 19
df[df["test_scores"] == 19]

   test_scores  quiz_scores      names
0           19           18  Apostolos

## 2. Reading data

### 2.1 Reading CSV files

Reading data with Python/pandas is super easy
Let's load the reviews data

In [61]:
# Load it to a DataFrame (assuming we're running from base directory)
df = pd.read_csv("../data/reviews.csv")
print(type(df))

<class 'pandas.core.frame.DataFrame'>

Let's explore it a little

In [62]:
df.describe()

       helpfulVotes    prcHelpful    totalVotes  productRating      verified
count  10000.000000  10000.000000  10000.000000   10000.000000  10000.000000
mean       3.948200      0.871846      4.871800       4.072200      0.734900
std       26.236687      0.280440     27.534389       1.331076      0.441409
min       -1.000000      0.000000     -1.000000       1.000000      0.000000
25%       -1.000000      0.967000     -1.000000       4.000000      0.000000
50%       -1.000000      1.000000     -1.000000       5.000000      1.000000
75%        2.000000      1.000000      3.000000       5.000000      1.000000
max     1410.000000      1.000000   1417.000000       5.000000      1.000000

In [63]:
df.head()

,reviewId,reviewerId,asin,review,title,dateWritten,helpfulVotes,prcHelpful,totalVotes,productRating,verified,badges
0,R1001D7IWN3HGH,AYGHDZICPFM42,B0011ZK6OS,I can't write a very technical review. I just...,great camera,2008-12-17 00:00:00,-1,1.0,-1,5.0,0,NaN
1,R1002DBICCTX81,AHAKLV81NL2MA,B00AQDG7YE,This little point and shoot can barely fit in ...,Wow!,2013-09-21 00:00:00,3,1.0,3,5.0,1,NaN
2,R1003U8MAJM7EG,A1BWH6MOLMHTIO,B00UKMBSE0,"I was not sure if I should go for a GoPro, and...",I used it to snorkel back in the Caribe and ev...,2014-08-15 00:00:00,-1,1.0,-1,5.0,1,NaN
3,R10052A11TEKY5,A12T9H67BA5R0K,B00393THEK,I would never go without a backup and this one...,Great product!,2013-10-12 00:00:00,-1,1.0,-1,5.0,1,NaN
4,R1006VVT7S8G2G,A17Z6JA6JUNF66,B00395YA90,Seems to offer lots of features plus quality. ...,Panasonic Lumix DMC ZS5,2010-09-05 00:00:00,-1,1.0,-1,4.0,1,NaN

In [64]:
df.tail()

,reviewId,reviewerId,asin,review,title,dateWritten,helpfulVotes,prcHelpful,totalVotes,productRating,verified,badges
9995,R175PKL1JS96M,A2OF14U27NJY7,B0090SLJDU,I got really sick of the iphone camera's crapp...,LOVE it! Perfect for having an alternative to ...,2012-12-12 00:00:00,-1,1.0,-1,5.0,1,NaN
9996,R175PV5GJ74QGS,A22NE4VSITL10W,B00HQ4W326,"Great Camera, excellent for an amateur photogr...",Great Camera for Amateur Photographer,2014-12-29 00:00:00,-1,1.0,-1,5.0,1,NaN
9997,R175T83I6ST0HL,AE3ZCISXLXB7Z,B004DEKH84,much more comfortable than the one that came w...,nice neck strap,2013-09-10 00:00:00,-1,1.0,-1,5.0,1,NaN
9998,R175VGA5M31CO3,A1AGU2SE3L8UAH,B0073AVSKG,There are things in this package that are grea...,"Some items good, others not.",2014-11-27 00:00:00,-1,1.0,-1,3.0,1,NaN
9999,R175VIVCB71T85,A1K6XKO9T0PK5P,B006UMM15O,This is a great little camera that packs a pun...,"Great camera, fast shipping!",2013-09-06 00:00:00,-1,1.0,-1,5.0,1,NaN

In [65]:
print(len(df))

10000

In [66]:
print(len(df.columns))

12

In [67]:
# The following returns the number of rows that have "verified" equal to 1
len(df[df["verified"] == 1])

7349

In [68]:
# How many verified reviews? (proportion)
df["verified"].mean()

np.float64(0.7349)

In [69]:
# What are the unique different possible ratings?
df["productRating"].unique()

array([5., 4., 3., 1., 2.])

### 2.3 Writing data

In [70]:
# Let's keep only two star reviews
df_twostar = df[df["productRating"] == 2]

# Let's write the new file
df_twostar.to_csv("../temp/reviews_2star.csv", index=False)

Super easy, right? And way way faster than Excel. And, as will become apparent, way more possibilities...

---

## PART 2: Analyzing data

We will now take a look into how to analyze data. 

We will also introduce pandas method "chaining", which helps us write code in a more readable way

In [73]:
# 1. Data
# Load the homes dataset
df_homes = pd.read_csv("../data/homes.csv")

# What is this data?
# This data contains information about homes in a county
# We can take a quick look at the dataset size and information
print(len(df_homes))
print(df_homes.columns.tolist())

32746
['tmp', 'yearbuilt', 'yearremodeled', 'usecode', 'condition', 'finsqft', 'cooling', 'fp_num', 'bedroom', 'fullbath', 'halfbath', 'totalrooms', 'city', 'zip', 'lotsize', 'landvalue', 'improvementsvalue', 'totalvalue', 'lastsaleprice', 'lastsaledate', 'age', 'med_age', 'fp', 'landuse', 'insub', 'remodel']

In [74]:
df_homes.head()

,tmp,yearbuilt,yearremodeled,usecode,condition,finsqft,cooling,fp_num,bedroom,fullbath,...,improvementsvalue,totalvalue,lastsaleprice,lastsaledate,age,med_age,fp,landuse,insub,remodel
0,006000000011B0,2006,0,Single Family,Average,1922,Central Air,1,3,3,...,300100,409900,0.0,2009-08-05T00:00:00Z,10.0,17.0,1,0,0,0
1,00600000003800,2003,0,Single Family,Average,1848,Central Air,0,3,2,...,79000,523100,0.0,1991-05-20T00:00:00Z,13.0,17.0,0,0,0,0
2,007000000018B0,1974,0,Single Family,Average,1368,No Central Air,0,3,1,...,128400,228800,0.0,1989-02-23T00:00:00Z,42.0,33.0,0,0,0,0
3,007000000042A0,1954,0,Single Family,Average,1092,No Central Air,0,4,1,...,77200,177900,0.0,2001-10-05T00:00:00Z,62.0,33.0,0,0,0,0
4,007000000042B0,1987,0,Single Family,Average,1344,Central Air,0,3,2,...,165900,232400,0.0,2009-05-20T00:00:00Z,29.0,33.0,0,0,0,0

In [75]:
df_homes.columns.tolist()

['tmp',
 'yearbuilt',
 'yearremodeled',
 'usecode',
 'condition',
 'finsqft',
 'cooling',
 'fp_num',
 'bedroom',
 'fullbath',
 'halfbath',
 'totalrooms',
 'city',
 'zip',
 'lotsize',
 'landvalue',
 'improvementsvalue',
 'totalvalue',
 'lastsaleprice',
 'lastsaledate',
 'age',
 'med_age',
 'fp',
 'landuse',
 'insub',
 'remodel']

In [76]:
# Or we can look at a summary of the data set to get some more advanced information
df_homes.describe()

,yearbuilt,yearremodeled,finsqft,fp_num,bedroom,fullbath,halfbath,totalrooms,zip,lotsize,landvalue,improvementsvalue,totalvalue,lastsaleprice,age,med_age,fp,landuse,insub,remodel
count,32746.000000,32746.000000,32746.000000,32746.000000,32746.000000,32746.000000,32746.000000,32746.000000,32490.000000,32746.000000,3.274600e+04,3.274600e+04,3.274600e+04,3.274500e+04,32745.000000,32745.000000,32746.000000,32746.000000,32746.000000,32746.000000
mean,1956.130306,139.372473,1944.679442,0.933702,3.232792,2.205460,0.565321,6.630031,22971.655894,4.631110,1.328489e+05,2.490682e+05,3.819171e+05,3.900473e+05,32.773553,28.078394,0.694925,0.049716,0.713156,0.069871
std,231.720697,508.767332,933.221573,0.873719,0.963218,0.936618,0.578771,2.497755,301.841535,22.102507,1.858939e+05,2.394328e+05,3.573200e+05,1.438328e+06,27.161985,5.192818,0.460446,0.217361,0.452295,0.254934
min,0.000000,0.000000,144.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22901.000000,0.000000,1.200000e+03,0.000000e+00,9.500000e+03,0.000000e+00,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000
25%,1973.000000,0.000000,1278.000000,0.000000,3.000000,2.000000,0.000000,5.000000,22901.000000,0.096000,6.600000e+04,1.219000e+05,1.959000e+05,0.000000e+00,16.000000,28.000000,0.000000,0.000000,0.000000,0.000000
50%,1987.000000,0.000000,1713.000000,1.000000,3.000000,2.000000,1.000000,7.000000,22911.000000,0.537000,1.050000e+05,1.920000e+05,2.999000e+05,1.570000e+05,28.000000,28.000000,1.000000,0.000000,1.000000,0.000000
75%,2000.000000,0.000000,2411.000000,1.000000,4.000000,3.000000,1.000000,8.000000,22932.000000,2.570000,1.459000e+05,2.948000e+05,4.437000e+05,3.230000e+05,43.000000,28.000000,1.000000,0.000000,1.000000,0.000000
max,2016.000000,2016.000000,8982.000000,13.000000,20.000000,11.000000,5.000000,87.000000,24590.000000,1067.150000,1.050170e+07,9.638500e+06,1.135230e+07,4.893700e+07,348.000000,50.000000,1.000000,1.000000,1.000000,1.000000

In [77]:
# How many conditions?
df_homes["condition"].unique()

array(['Average', 'Fair', 'Good', 'Poor', nan, 'Substandard', 'Excellent'],
      dtype=object)

## 2. Pandas: isolating data

In [ ]:
# 2.1 The select operation
# This operation is used to extract columns from our data by using their name

# For example, let's say we want to extract the total value column
values = df_homes[["totalvalue"]]  # Double brackets return DataFrame
values.mean()  # This works because values is a DataFrame

totalvalue    381917.073841
dtype: float64

In [88]:
# Alternatively, single brackets return a "Series"
values_series = df_homes["totalvalue"]
print(values_series.mean())
print(type(values_series))

381917.07384107984
<class 'pandas.core.series.Series'>

In [90]:
# Let's say we want to extract more than one column
df_new = df_homes[["totalvalue", "yearbuilt"]]
df_new

       totalvalue  yearbuilt
0          409900       2006
1          523100       2003
2          228800       1974
3          177900       1954
4          232400       1987
...           ...        ...
32741      710000       2004
32742      752400       2003
32743      239700       1992
32744      298400       1971
32745      196100       1955

[32746 rows x 2 columns]

In [92]:
# If we want all columns except certain ones
df_new = df_homes.drop(["yearbuilt"], axis=1)
df_new

,tmp,yearremodeled,usecode,condition,finsqft,cooling,fp_num,bedroom,fullbath,halfbath,...,improvementsvalue,totalvalue,lastsaleprice,lastsaledate,age,med_age,fp,landuse,insub,remodel
0,006000000011B0,0,Single Family,Average,1922,Central Air,1,3,3,0,...,300100,409900,0.0,2009-08-05T00:00:00Z,10.0,17.0,1,0,0,0
1,00600000003800,0,Single Family,Average,1848,Central Air,0,3,2,0,...,79000,523100,0.0,1991-05-20T00:00:00Z,13.0,17.0,0,0,0,0
2,007000000018B0,0,Single Family,Average,1368,No Central Air,0,3,1,0,...,128400,228800,0.0,1989-02-23T00:00:00Z,42.0,33.0,0,0,0,0
3,007000000042A0,0,Single Family,Average,1092,No Central Air,0,4,1,0,...,77200,177900,0.0,2001-10-05T00:00:00Z,62.0,33.0,0,0,0,0
4,007000000042B0,0,Single Family,Average,1344,Central Air,0,3,2,0,...,165900,232400,0.0,2009-05-20T00:00:00Z,29.0,33.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32741,031C0000004500,0,Single Family,Good,3572,Central Air,1,4,4,1,...,560000,710000,0.0,2005-06-29T00:00:00Z,12.0,31.0,1,0,1,0
32742,031C0000004700,0,Single Family,Good,3575,Central Air,1,4,4,1,...,602400,752400,136500.0,2003-05-20T00:00:00Z,13.0,31.0,1,0,1,0
32743,032000000004L2,0,Single Family,Good,1799,No Central Air,0,5,3,0,...,189700,239700,239500.0,2016-03-17T00:00:00Z,24.0,28.0,0,0,1,0
32744,032000000009J0,0,Single Family,Good,1912,Central Air,1,3,3,0,...,185800,298400,0.0,2016-05-04T00:00:00Z,45.0,28.0,1,0,0,0
32745,032000000024A0,0,Single Family,Average,1062,Central Air,1,3,1,0,...,101600,196100,175000.0,2003-12-17T00:00:00Z,61.0,28.0,1,0,0,0

In [93]:
# 2.2 The filter operation
# This operation keeps only rows that satisfy a condition

# Keep only houses built in 2015
df_new = df_homes[df_homes["yearbuilt"] == 2015]
print(f"There are {len(df_new)} houses built in 2015 (out of {len(df_homes)} total)")

There are 419 houses built in 2015 (out of 32746 total)

In [94]:
# Keep houses built after 2015
df_new = df_homes[df_homes["yearbuilt"] > 2015]
print(f"There are {len(df_new)} houses built after 2015 (out of {len(df_homes)} total)")

There are 351 houses built after 2015 (out of 32746 total)

In [95]:
# Keep houses that were built in 2011, 2013, or 2015
df_new = df_homes[df_homes["yearbuilt"].isin([2011, 2013, 2015])]
print(f"There are {len(df_new)} houses built in 2011, 2013, or 2015 (out of {len(df_homes)} total)")

There are 1148 houses built in 2011, 2013, or 2015 (out of 32746 total)

In [96]:
# Keep houses that are either in Scottsville or Crozet
df_new = df_homes[df_homes["city"].isin(["SCOTTSVILLE", "CROZET"])]
print(f"There are {len(df_new)} houses in Scottsville or Crozet (out of {len(df_homes)} total)")

There are 4095 houses in Scottsville or Crozet (out of 32746 total)

In [97]:
# Keep houses with the maximum number of bedrooms
max_bedrooms = df_homes["bedroom"].max()
df_new = df_homes[df_homes["bedroom"] == max_bedrooms]
print(f"There are {len(df_new)} houses with the maximum number of bedrooms ({max_bedrooms}) (out of {len(df_homes)} total)")

There are 1 houses with the maximum number of bedrooms (20) (out of 32746 total)

In [99]:
# Alternatively
df_new = df_homes[df_homes["bedroom"] == df_homes["bedroom"].max()]
print(f"There are {len(df_new)} houses with the maximum number of bedrooms ({max_bedrooms}) (out of {len(df_homes)} total)")

There are 1 houses with the maximum number of bedrooms (20) (out of 32746 total)

In [105]:
# Multiple conditions
df_homes_crozet = df_homes[df_homes["city"] == "CROZET"]
df_new = df_homes[
    (df_homes["city"] == "CROZET") & (df_homes["finsqft"] > df_homes_crozet["finsqft"].mean())
]
print(f"There are {len(df_new)} houses in Crozet with a larger floor area than the average house in Crozet (out of {len(df_homes_crozet)} total houses in Crozet)")

There are 1389 houses in Crozet with a larger floor area than the average house in Crozet (out of 3018 total houses in Crozet)

In [111]:
# find unique cities
df_homes["city"].unique()

array(['CROZET', 'OTHER', 'EARLYSVILLE', 'CHARLOTTESVILLE', 'ESMONT',
       'SCOTTSVILLE', 'BARBOURSVILLE', 'AFTON', 'NORTH GARDEN', 'KESWICK'],
      dtype=object)

# 2.3 The sort operation

In [108]:
# This operation helps us sort according to whatever we want
df_new = df_homes.sort_values("finsqft", ascending=False)
df_new[["yearbuilt", "condition", "finsqft", "totalvalue", "city"]].head()

       yearbuilt  condition  finsqft  totalvalue             city
7658        1998       Good     8982     6024200  CHARLOTTESVILLE
9010        1940       Good     8897     3215500      EARLYSVILLE
8558        2015    Average     8878     4188000     NORTH GARDEN
21298       2009    Average     8849     2125800            OTHER
23304       2008  Excellent     8829     4199400  CHARLOTTESVILLE

In [112]:
# sort in ascending order
df_new = df_homes.sort_values("finsqft", ascending=True)
df_new[["yearbuilt", "condition", "finsqft", "totalvalue", "city"]].head()

       yearbuilt condition  finsqft  totalvalue             city
24991       1952      Poor      144      218100           CROZET
23198          0       NaN      221      535800            OTHER
5860        1995   Average      231      102800            OTHER
30070       1982   Average      261      111100  CHARLOTTESVILLE
21295       1955   Average      300      143800            OTHER

## 3. Pandas: method chaining

Sometimes we want to perform many operations on a dataset

For example, let's say we want to 
1. only select houses in Crozet
2. only keep the "totalvalue", and "lotsize" columns, and
3. sort our data by decreasing lotsize order

In [113]:
# Doing it step by step
df_crozet = df_homes[df_homes["city"] == "CROZET"]
df_crozet = df_crozet[["totalvalue", "lotsize"]]
df_crozet = df_crozet.sort_values("lotsize", ascending=False)
df_crozet.head()

       totalvalue  lotsize
30915     1975300  620.430
20923     2391000  453.893
152       1111500  288.139
20960      740800  261.711
30916     1260700  231.100

In [115]:
# Or we can chain the operations together:
df_crozet_2 = df_homes[df_homes["city"] == "CROZET"][["totalvalue", "lotsize"]].sort_values("lotsize", ascending=False)
df_crozet_2.head()

       totalvalue  lotsize
30915     1975300  620.430
20923     2391000  453.893
152       1111500  288.139
20960      740800  261.711
30916     1260700  231.100

## 4. Pandas: deriving data

We can create new columns using assignment

In [119]:

# Create a copy of the data to work with
df_new = df_homes.copy()

# Create a new column by dividing two existing columns
df_new["value_sqft"] = df_new["totalvalue"] / df_new["finsqft"]

# Select only the columns we want and sort by value per square foot
df_new = df_new[["yearbuilt", "condition", "finsqft", "totalvalue", "city", "value_sqft"]]
df_new = df_new.sort_values("value_sqft", ascending=False)

df_new.head()

       yearbuilt condition  finsqft  totalvalue             city   value_sqft
17147          0   Average     1210    10351200          KESWICK  8554.710744
19585       1935   Average      475     3931500            OTHER  8276.842105
16218       1962   Average     1590    11352300  CHARLOTTESVILLE  7139.811321
25347       1934   Average      600     3931500            OTHER  6552.500000
8079           0      Fair      731     4153300            OTHER  5681.668947

In [120]:
# We can also create conditional columns
# First, let's create the value_sqft column again
df_new = df_homes.copy()
df_new["value_sqft"] = df_new["totalvalue"] / df_new["finsqft"]

# Create a column that shows if a house has high value per sqft
median_value_sqft = df_new["value_sqft"].median()
df_new["high_value_sqft"] = df_new["value_sqft"] > median_value_sqft

# Select columns and sort
df_new = df_new[["yearbuilt", "condition", "finsqft", "totalvalue", "city", "value_sqft", "high_value_sqft"]]
df_new = df_new.sort_values("value_sqft", ascending=False)

df_new.head()

,yearbuilt,condition,finsqft,totalvalue,city,value_sqft,high_value_sqft
17147,0,Average,1210,10351200,KESWICK,8554.710744,True
19585,1935,Average,475,3931500,OTHER,8276.842105,True
16218,1962,Average,1590,11352300,CHARLOTTESVILLE,7139.811321,True
25347,1934,Average,600,3931500,OTHER,6552.500000,True
8079,0,Fair,731,4153300,OTHER,5681.668947,True

In [121]:
# Creating multiple new columns at once
df_new = df_homes.copy()

# Create value per square foot
df_new["value_sqft"] = df_new["totalvalue"] / df_new["finsqft"]

# Create remodel indicator (1 if remodeled, 0 if not)
df_new["remodel"] = (df_new["yearremodeled"] > 0).astype(int)

# Select only the columns we want and sort
df_new = df_new[["value_sqft", "remodel", "city"]]
df_new = df_new.sort_values("value_sqft")

df_new.head()

       value_sqft  remodel             city
31112    7.620818        0  CHARLOTTESVILLE
4230    10.772358        0           ESMONT
28570   11.020882        0            OTHER
18469   12.104489        0            OTHER
19276   13.699495        0            OTHER

Sometimes, we want to calculate summary statistics for our data

In [122]:
# First, filter houses with yearbuilt info
df_homes_filtered = df_homes[df_homes["yearbuilt"] > 0]

# Compute summary statistics and save them in a new dataframe
df_homes_stats = df_homes_filtered.agg({"yearbuilt": ["min", "max", "count", "mean", "median"]}).round(2)

df_homes_stats

        yearbuilt
min        1668.0
max        2016.0
count     32299.0
mean       1983.2
median     1988.0

Group by is a powerful operation that allows us to group data by a certain column and then apply a function to each group. 
- This is useful when we want to calculate summary statistics for our data by group.
- See also the `query` operation, which is a more readable way to filter data.
- Notice the `reset_index()` operation, which is used to reset the index from city to the usual row index.

In [ ]:
# Group by city and compute summary statistics
df_homes_stats = (
    df_homes
    .query("yearbuilt > 0") # keep only houses with yearbuilt info
    .groupby("city")["yearbuilt"] # group by city and then select the column we will apply the following functions to
    .agg(["min", "max", "count", "mean", "median"]) # apply the min, max, count, mean, and median "aggregation" functions to each group
    .round(2) # round results to 2 decimal places
    .reset_index() # "ungroup" --> resets the index from city to "per row"
)

df_homes_stats

              city   min   max  count     mean  median
0            AFTON  1756  2015    495  1970.54  1981.0
1    BARBOURSVILLE  1800  2016    405  1983.60  1988.0
2  CHARLOTTESVILLE  1668  2016  21006  1985.40  1988.0
3           CROZET  1700  2016   2978  1984.99  1999.0
4      EARLYSVILLE  1735  2016   1909  1982.39  1985.0
5           ESMONT  1740  2016    478  1966.10  1980.0
6          KESWICK  1724  2016   1574  1986.63  1995.0
7     NORTH GARDEN  1700  2016    603  1968.20  1980.0
8            OTHER  1730  2016   1811  1972.30  1978.0
9      SCOTTSVILLE  1732  2016   1040  1971.34  1979.0

Adding within-group quantities is a little trickier.

Here, we'll add information about whether a house is newer than the median year built in its city.

In [126]:
# First, filter houses with yearbuilt info
df_homes_filtered = df_homes[df_homes["yearbuilt"] > 0].copy()

# Calculate median year built by city
median_by_city = df_homes_filtered.groupby("city")["yearbuilt"].median()

median_by_city

city
AFTON              1981.0
BARBOURSVILLE      1988.0
CHARLOTTESVILLE    1988.0
CROZET             1999.0
EARLYSVILLE        1985.0
ESMONT             1980.0
KESWICK            1995.0
NORTH GARDEN       1980.0
OTHER              1978.0
SCOTTSVILLE        1979.0
Name: yearbuilt, dtype: float64

In [130]:
# now we'll add the median back to our dataframe
# the `map` function will match each city from the two dataframes and add the median year built for that city
df_homes_filtered["median_yearbuilt"] = df_homes_filtered["city"].map(median_by_city)
df_homes_filtered= df_homes_filtered[["yearbuilt", "condition", "finsqft", "city", "median_yearbuilt"]]
df_homes_filtered.head()

   yearbuilt condition  finsqft    city  median_yearbuilt
0       2006   Average     1922  CROZET            1999.0
1       2003   Average     1848  CROZET            1999.0
2       1974   Average     1368   OTHER            1978.0
3       1954   Average     1092   OTHER            1978.0
4       1987   Average     1344   OTHER            1978.0

In [131]:
# and we can create a new column indicating if house is newer than city median
df_homes_filtered["new"] = (df_homes_filtered["yearbuilt"] >= df_homes_filtered["median_yearbuilt"]).astype(int)
df_homes_filtered.head()

   yearbuilt condition  finsqft    city  median_yearbuilt  new
0       2006   Average     1922  CROZET            1999.0    1
1       2003   Average     1848  CROZET            1999.0    1
2       1974   Average     1368   OTHER            1978.0    0
3       1954   Average     1092   OTHER            1978.0    0
4       1987   Average     1344   OTHER            1978.0    1

We can group by more than one variable

In [132]:
# You can group by more than one variable
# Group by both city and the "new" indicator we just created
df_homes_stats = (
    df_homes_filtered
    .groupby(["city", "new"])["yearbuilt"]
    .agg(["min", "max", "count", "mean", "median"])
    .round(2)
    .reset_index()
)

df_homes_stats.head()

              city  new   min   max  count     mean  median
0            AFTON    0  1756  1980    243  1943.60  1960.0
1            AFTON    1  1981  2015    252  1996.52  1996.0
2    BARBOURSVILLE    0  1800  1987    192  1965.51  1973.0
3    BARBOURSVILLE    1  1988  2016    213  1999.91  2001.0
4  CHARLOTTESVILLE    0  1668  1987  10426  1970.46  1974.0